from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start{CMD_INDEX}'
        self.MirrorCommand = f'm1{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipm1{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipm1{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'drive{CMD_INDEX}'
        self.SearchCommand = f'cari{CMD_INDEX}'
        self.StatusCommand = f'status{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo{CMD_INDEX}'
        self.PingCommand = f'p{CMD_INDEX}'
        self.RestartCommand = f'baleni{CMD_INDEX}'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.SpeedCommand = f'speedtest{CMD_INDEX}'
        self.CloneCommand = f'c{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'w1{CMD_INDEX}'
        self.ZipWatchCommand = f'zipw1{CMD_INDEX}'
        self.QbMirrorCommand = f'qbm1{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipm1{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipm1{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'le1{CMD_INDEX}'
        self.UnzipLeechCommand = f'unziple1{CMD_INDEX}'
        self.ZipLeechCommand = f'ziple1{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunziple1{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbziple1{CMD_INDEX}'
        self.LeechWatchCommand = f'leechw1{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipw1{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'

BotCommands = _BotCommands()
